<div class="search-map__map" id='map' style="height:300px">


<script>
    var test = require(["jquery","https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"], function ($,L) {
        $('head').append(`<link rel="stylesheet" 
                            href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
                            integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
                            crossorigin=""
                    >`);
        var map = L.map('map').setView([51.505, -0.09], 13);
        L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png', {
            attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a>',
            maxZoom: 18
        }).addTo(map);
    })
</script>