<h1>UI Components Example</h1>

<div data-mage-init='{"Magento_Ui/js/core/app": <?= $block->getJsLayout() ?>}'
>

    <div data-bind="scope:'parent'">
    <!-- ko template: getTemplate() -->
    <!-- /ko -->
    </div>
    <br/>

    <div data-bind="scope:'example'">
    <!-- ko template: getTemplate() -->
    <!-- /ko -->
    </div>
    <br/>

    <div data-bind="scope:'exports'">
    <!-- ko template: getTemplate() -->
    <!-- /ko -->
    </div>
    <br/>

    <div data-bind="scope:'imports'">
    <!-- ko template: getTemplate() -->
    <!-- /ko -->
    </div>
    <br/>

    <div data-bind="scope: 'links'">
    <!-- ko template: getTemplate() -->
    <!-- /ko -->
    </div>
    <br/>
    <br/>

</div>
