<h1>CONTENT</h1>
<div class="collapsible" data-mage-init='{
    "collapsible":{
        "collapsible": true,
        "openedState": "active",
        "active": true,
        "saveState": true
    }}'>

    <div class="collapsible__title" data-role="title" class="button" style="display:flex; align-items: center;" >
        <h4>Fruit</h4>
        <p class="collapsible__trigger" data-role="trigger">
            <svg width="800px" height="800px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
                <path d="M12 4L12 20M12 20L18 14M12 20L6 14" stroke="#1C274C" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/>
            </svg>
        </p>
    </div>
    
    <div data-role="content">
        <ul>
            <li>Orange</li>
            <li>Apple</li>
            <li>Banana</li>
        </ul>
    </div>
</div>